config/routes.rb
Rails.application.routes.draw do
  
  
  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  
  get 'help'    => 'static_pages#help'
  
  get 'about'   => 'static_pages#about'
  
  get 'contact' => 'static_pages#contact'
  
  get 'signup'  => 'users#new'
  
  get 'login'   => "sessions#new"
  post 'login'  => "sessions#create"
  delete 'logout' => "sessions#destroy"
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create,:destroy]

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates(:content, presence: true, length: {maximum: 140})
  validates(:user_id, presence: true)
  default_scope -> { order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  attr_accessor :remember_token, :activation_token
  before_save :downcase_mail
  before_create :create_activation_digest
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:name , presence: true, length:{maximum:50})
  validates(:email, presence: true, length:{maximum:255}, format:{with: VALID_EMAIL_REGEX}, uniqueness:{case_sensitive:false})
  
  has_secure_password
  validates(:password, length:{minimum:6}, allow_blank:true)
  
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? Bcrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost:cost)
  end
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(self.remember_token))
  end
  
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end
  
  def send_activation_email
     UserMailer.account_activation(self).deliver_now
  end
  
  def feed 
    Micropost.where("user_id=?",id)
  end
  
  private
  
  def downcase_mail
    self.email = email.downcase
  end
  
  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
 
 def edit
    user = User.find_by(email:params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.activate
      log_in(user)
      flash[:sucess] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Please check your email and activate your account"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      redirect_to 'static_page/home'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted!"
    redirect_to request.referrer || root_url
  end
  
  private
  
  def micropost_params
    params.require(:micropost).permit(:content)
  end
  
  def correct_user
    @micropost = current_user.microposts.find_by(id:params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
     
  end
  
  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in(user)
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_to user
      else
        message = "Account not yet activated"
        message += "Please check your email and activate your account"
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    log_out if logged_in? 
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page:params[:page])
    end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def index 
    @users = User.paginate(page: params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] ="Please check your email and activate your account"
      #log_in(@user)
      #redirect_back_to(@user)
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find_by(params[:id])
  end
  
  def update
    @user = User.find_by(params[:id])
    if @user.update_attributes(user_params)
      #handle success
      flash[:success] ="Profile updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find_by(id: params[:id]).destroy
    flash["success"] = "User deleted"
    redirect_to users_url
  end
  
  def correct_user
    @user = User.find_by(params[:id])
    redirect_to root_url unless currect_user?(@user)
  end
  
  private 
   def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end
   
   def admin_user
     redirect_to root_url unless current_user.admin?
   end
   
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title='')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
  def current_user
    #if @current_user.nil?
    #  User.find_by(id: session[:user_id])
    #else
    #  @current_user
    #end
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
  def current_user?(user)
    user == @current_user
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def is_logged_in?
    !session[:user_id].nil?
  end
  
  def log_out
      forget(@current_user)
      session.delete(:user_id)
      @current_user = nil
  end
  
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
  
  def redirect_back_to(user)
    redirect_to(session[:forwarding_url] || user)
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt:user.name, class:"gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://wwww.railstutorial.org/">Ruby on Rails Tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "News", "http://news.railstutorial.org" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    
    <%= link_to "sample_app", root_path, id:"logo"%>
    
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to "Home", root_path %> </li>
        <li> <%= link_to "Help", help_path %> </li>
        <% if logged_in? %>
          <li> <%= link_to "Users", users_path %> </li>
          <li class="dropdown">
             <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
               Account <b class="caret"></b>
             </a>
             <ul class="dropdown-menu">
                <li> <%= link_to "Profile", current_user %> </li>
                <li> <%= link_to "Settings", edit_user_path(current_user) %> </li>
                <li class="divider"></li>
                <li> <%= link_to "Log Out", logout_path, method: "delete" %> </li>
             </ul>
          </li>
          <%else%>
            <li> <%= link_to "Log in", login_path %> </li>
          <%end%>
      </ul>
    </nav>
    
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  
  
    <div class="container">
     
      <% flash.each do |msg_type,msg| %>
      <div class="alert alert-<%= msg_type%>"><%= msg%></div>
      <%end%>
      
      <%= yield %>
    
      <%= render 'layouts/footer' %>
  
    <%= debug(params) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%=micropost.id %>" >
  <span class ="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class ="content"><%= micropost.content %></span>
  <span class ="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at)%> |
    <%= link_to "delete", micropost, method: :delete, data: {confirm:"You Sure?"} %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
 <% if object.errors.any? %>
    <div id="error_explanantion">
        <div class="alert alert-danger">
          The form contains <%= pluralize(object.errors.count, "error") %>.
          
        </div>
        <ul>
          <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <%end%>
        </ul>
    </div>
  <%end%>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: "compose new micropost" %>
</div>
<%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
 <%= link_to gravatar_for(current_user, size:50), current_user %>
 <h1><%= current_user.name %></h1>
 <span><%= link_to "view my profile", current_user %></span>
 <span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<%provide(:title,"About") %>

    <h1>StaticPages#about</h1>
    <p>Find me in app/views/static_pages/about.html.erb</p>
 

app/views/static_pages/contact.html.erb
<%provide(:title,"Contact") %>

    <h1>StaticPages#contact</h1>
    <p>Find me in app/views/static_pages/contact.html.erb</p>
  

app/views/static_pages/help.html.erb
<%provide(:title,"Help") %>

    <h1>StaticPages#help</h1>
    <p>Find me in app/views/static_pages/help.html.erb</p>
  

app/views/static_pages/home.html.erb
  <% if logged_in? %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
          <%= render 'shared/micropost_form' %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3>Micropost feed</h3>
        <%= render 'shared/feed'%>
      </div>
    </div>
  <% else %>
  <div class="center jumbotron">
    <h1> Welcome to the Sample App</h1>
    
    <h2>
      This is home page for the 
      <a href="https://www.railstutorial.org/"> Ruby on Rails Tutorial</a>
      Sample Application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
  <%= link_to image_tag("rails.png", alt: "Rails logo") , 'http://rubyonrails.org/' %>
  <% end %>

app/views/users/edit.html.erb
<%provide(:title,"Edit User") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages, object: f.object' %>
     
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class:'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class:'form-control' %>
      
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class:'form-control' %>
      
      <%= f.submit "Save changes", class:"btn btn-primary submit" %>
    <% end %>
    
    <div class="gravatar-edit">
      <%= gravatar_for @user %>
      <a href="http://gravatr.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
  <h1>All Users</h1>
  <%= will_paginate %>
      <ul class="users">
        <% @users.each do |user| %>
          <% if user.activated? %>
            <li>
              <%= gravatar_for user, size: 50 %>
              <%= link_to user.name, user%>
              <% if current_user.admin? && !current_user?(user)%>
                | <%= link_to "delete", user, method: :delete, data: {confirm: "You Sure?"} %>
              <% end %>
            </li>
          <% end %>
        <% end %>
      </ul>
  <%= will_paginate %>
      

app/views/users/new.html.erb
<%provide(:title,"SignUp") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages, object: f.object' %>
     
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class:'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class:'form-control' %>
      
      <%= f.label :password_confirmation%>
      <%= f.password_field :password_confirmation, class:'form-control' %>
      
      <%= f.submit "Create my account", class:"btn btn-primary submit" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user%>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div class="col-md-8">
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
    <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>